### ISSUE TITLE
lab2: crashes on first run with ogr error

### ISSUE THREAD

**Issue by billspat** [SpaCE-Lab-MSU/MSUGradSpatialEcology#2]
I think this is because the command dir.create for the data path does not have recursive=TRUE so only the 'data' folder is being created the first time, no 'lab2' folder, so the download and read errors. 

then the second time the whole path is being created and it works

**Comment by plzmsu** [comment]
ok - let me know when the site is updated (can you update it today?) and I'll have them reference the new Rmd file.

**Comment by billspat** [comment]
closed with 47ee3b2  and site is updated.     Other than re-downloading the lab2 Rmd file, they can 1) run twice 2) make sure to create a folder "output" if there isn't one already.
