### ISSUE TITLE
Lab5 and re-rendering not working

### ISSUE THREAD

**Issue by plzmsu** [SpaCE-Lab-MSU/MSUGradSpatialEcology#7]
I added the .Rmd files and PDF files associated w Lab5. It looks great when I do: rmarkdown: render_site("lab5_variograms.Rmd") but when I try to do the whole site with rmarkdown: render_site() there are issues popping up in previous labs for some reason.

Any ideas? @billspat 

I didn't commit the .html versions in /docs in case that messes it up.

**Comment by billspat** [comment]
what happens when you, say render an earlier lab by itself like you did lab5?      It could be that some Rmd files have side effects that break the next lab.   Would you please post the error messages either here or as new github issues?  TBH  I haven't taken the time to fix the labs on my own computer and use the working fdata links etc so I'm sure I would have issues also if I re-rendered them as is.

**Comment by plzmsu** [comment]
Entire site rendering:



R version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> rmarkdown::render_site()

Rendering: ./index.Rmd
  |.......................................................................................| 100%
  ordinary text without R code


/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS index.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output index.html --email-obfuscation none --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --include-before-body /var/folders/ry/9bc9_2p54c94dtmtxzy91dxm0000gv/T//Rtmp1Q8htE/rmarkdown-str236278e8b22.html --variable navbar=1 --variable body_padding=51 --variable header_padding=56 --variable 'theme:bootstrap' --include-in-header /var/folders/ry/9bc9_2p54c94dtmtxzy91dxm0000gv/T//Rtmp1Q8htE/rmarkdown-str23621f50690e.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/latex-div.lua 

Rendering: ./lab1_R.Rmd
  |..........                                                                             |  11%
  ordinary text without R code

  |...................                                                                    |  22%
label: unnamed-chunk-1 (with options) 
List of 2
 $ message: logi FALSE
 $ warning: logi FALSE

  |.............................                                                          |  33%
  ordinary text without R code

  |.......................................                                                |  44%
label: unnamed-chunk-2 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |................................................                                       |  56%
  ordinary text without R code

  |..........................................................                             |  67%
label: unnamed-chunk-3
  |....................................................................                   |  78%
  ordinary text without R code

  |.............................................................................          |  89%
label: unnamed-chunk-4 (with options) 
List of 1
 $ message: logi FALSE

  |.......................................................................................| 100%
  ordinary text without R code


/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS lab1_R.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output lab1_R.html --email-obfuscation none --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --include-before-body /var/folders/ry/9bc9_2p54c94dtmtxzy91dxm0000gv/T//Rtmp1Q8htE/rmarkdown-str236275774335.html --variable navbar=1 --variable body_padding=51 --variable header_padding=56 --variable 'theme:bootstrap' --include-in-header /var/folders/ry/9bc9_2p54c94dtmtxzy91dxm0000gv/T//Rtmp1Q8htE/rmarkdown-str236268dd88d2.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/latex-div.lua 

Rendering: ./lab2_scale.Rmd
  |.....                                                                                  |   6%
  ordinary text without R code

  |..........                                                                             |  11%
label: unnamed-chunk-1
  |..............                                                                         |  17%
label: unnamed-chunk-2 (with options) 
List of 1
 $ results: chr "hide"

  |...................                                                                    |  22%
  ordinary text without R code

  |........................                                                               |  28%
label: unnamed-chunk-3 (with options) 
List of 1
 $ echo: logi FALSE

  |.............................                                                          |  33%
  ordinary text without R code

  |..................................                                                     |  39%
label: unnamed-chunk-4 (with options) 
List of 3
 $ echo  : logi FALSE
 $ height: num 3
 $ width : num 4

  |.......................................                                                |  44%
  ordinary text without R code

  |............................................                                           |  50%
label: unnamed-chunk-5 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |................................................                                       |  56%
  ordinary text without R code

  |.....................................................                                  |  61%
label: unnamed-chunk-6 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |..........................................................                             |  67%
  ordinary text without R code

  |...............................................................                        |  72%
label: unnamed-chunk-7 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |....................................................................                   |  78%
  ordinary text without R code

  |........................................................................               |  83%
label: unnamed-chunk-8 (with options) 
List of 2
 $ message: logi FALSE
 $ warning: logi FALSE

Error in x$.self$finalize() : attempt to apply non-function
In addition: Warning messages:
1: In readOGR(file.path(data_path, "cb_2014_us_nation_20m.shp")) :
  Z-dimension discarded
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum unknown in CRS definition
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in x$.self$finalize() : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
Error in (function (x)  : attempt to apply non-function
  |.............................................................................          |  89%
  ordinary text without R code

  |..................................................................................     |  94%
label: unnamed-chunk-9 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

trying URL 'http://www2.census.gov/geo/tiger/GENZ2014/shp/cb_2014_us_region_20m.zip'
Content type 'application/zip' length 108492 bytes (105 KB)
==================================================
downloaded 105 KB

  |.......................................................................................| 100%
  ordinary text without R code


/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS lab2_scale.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output lab2_scale.html --email-obfuscation none --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --include-before-body /var/folders/ry/9bc9_2p54c94dtmtxzy91dxm0000gv/T//Rtmp1Q8htE/rmarkdown-str2362222dc79d.html --variable navbar=1 --variable body_padding=51 --variable header_padding=56 --variable 'theme:bootstrap' --include-in-header /var/folders/ry/9bc9_2p54c94dtmtxzy91dxm0000gv/T//Rtmp1Q8htE/rmarkdown-str23626b8c25f2.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/latex-div.lua 

Rendering: ./lab3_patch_design.Rmd
  |....                                                                                   |   4%
  ordinary text without R code

  |........                                                                               |   9%
label: unnamed-chunk-1 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |...........                                                                            |  13%
  ordinary text without R code

  |...............                                                                        |  17%
label: unnamed-chunk-2 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |...................                                                                    |  22%
  ordinary text without R code

  |.......................                                                                |  26%
label: unnamed-chunk-3 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |..........................                                                             |  30%
  ordinary text without R code

  |..............................                                                         |  35%
label: unnamed-chunk-4 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |..................................                                                     |  39%
  ordinary text without R code

  |......................................                                                 |  43%
label: unnamed-chunk-5 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |..........................................                                             |  48%
  ordinary text without R code

  |.............................................                                          |  52%
label: unnamed-chunk-6 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |.................................................                                      |  57%
  ordinary text without R code

  |.....................................................                                  |  61%
label: unnamed-chunk-7 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |.........................................................                              |  65%
  ordinary text without R code

  |.............................................................                          |  70%
label: unnamed-chunk-8 (with options) 
List of 4
 $ message   : logi FALSE
 $ warning   : logi FALSE
 $ fig.width : num 6
 $ fig.height: num 8

  |................................................................                       |  74%
  ordinary text without R code

  |....................................................................                   |  78%
label: unnamed-chunk-9 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |........................................................................               |  83%
  ordinary text without R code

  |............................................................................           |  87%
label: unnamed-chunk-10 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |...............................................................................        |  91%
  ordinary text without R code

  |...................................................................................    |  96%
label: unnamed-chunk-11 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |.......................................................................................| 100%
  ordinary text without R code


/Applications/RStudio.app/Contents/MacOS/pandoc/pandoc +RTS -K512m -RTS lab3_patch_design.utf8.md --to html4 --from markdown+autolink_bare_uris+tex_math_single_backslash --output lab3_patch_design.html --email-obfuscation none --standalone --section-divs --template /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/h/default.html --no-highlight --variable highlightjs=1 --include-before-body /var/folders/ry/9bc9_2p54c94dtmtxzy91dxm0000gv/T//Rtmp1Q8htE/rmarkdown-str236261c74ce1.html --variable navbar=1 --variable body_padding=51 --variable header_padding=56 --variable 'theme:bootstrap' --include-in-header /var/folders/ry/9bc9_2p54c94dtmtxzy91dxm0000gv/T//Rtmp1Q8htE/rmarkdown-str2362638879ed.html --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/pagebreak.lua --lua-filter /Library/Frameworks/R.framework/Versions/4.0/Resources/library/rmarkdown/rmd/lua/latex-div.lua 

Rendering: ./lab4_autocorrelation.Rmd
  |.....                                                                                  |   6%
  ordinary text without R code

  |..........                                                                             |  12%
label: unnamed-chunk-1 (with options) 
List of 1
 $ echo: logi FALSE

  |...............                                                                        |  18%
   inline R code fragments

  |....................                                                                   |  24%
label: unnamed-chunk-2 (with options) 
List of 2
 $ message: logi FALSE
 $ warning: logi FALSE

  |..........................                                                             |  29%
  ordinary text without R code

  |...............................                                                        |  35%
label: unnamed-chunk-3 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

  |....................................                                                   |  41%
  ordinary text without R code

  |.........................................                                              |  47%
label: unnamed-chunk-4 (with options) 
List of 3
 $ message: logi FALSE
 $ results: chr "hide"
 $ warning: logi FALSE

Error in FUN(X[[i]], ...) : object 'bryce_NED_1' not found
In addition: Warning messages:
1: In readOGR(file.path(data_path, "cb_2014_us_region_20m.shp")) :
  Z-dimension discarded
2: In readOGR(file.path(data_path, "cb_2014_us_state_20m.shp")) :
  Z-dimension discarded
3: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded ellps WGS 84 in CRS definition: +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs
4: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum WGS_1984 in CRS definition
5: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded ellps WGS 84 in CRS definition: +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs
6: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum WGS_1984 in CRS definition
7: Transformation introduced infinite values in continuous x-axis 
8: Removed 3943 rows containing non-finite values (stat_density). 
9: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition

**Comment by plzmsu** [comment]
Lab2 rendering alone: (these errors are the same I was getting earlier in the semester but it still renders)

Output created: docs/lab2_scale.html
Warning messages:
1: In readOGR(file.path(data_path, "cb_2014_us_nation_20m.shp")) :
  Z-dimension discarded
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum unknown in CRS definition
3: In unzip(file.path(data_path, "usr.zip"), exdir = data_path) :
  error 1 in extracting from zip file
4: In readOGR(file.path(data_path, "cb_2014_us_region_20m.shp")) :
  Z-dimension discarded

**Comment by plzmsu** [comment]
Lab3 rendering alone: 

Output created: docs/lab3_patch_design.html
Warning messages:
1: In readOGR(file.path(data_path, "cb_2014_us_state_20m.shp")) :
  Z-dimension discarded
2: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded ellps WGS 84 in CRS definition: +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs
3: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum WGS_1984 in CRS definition
4: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded ellps WGS 84 in CRS definition: +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs
5: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum WGS_1984 in CRS definition
6: Transformation introduced infinite values in continuous x-axis 
7: Removed 3943 rows containing non-finite values (stat_density).

**Comment by plzmsu** [comment]
Lab4 alone:

Output created: docs/lab4_autocorrelation.html
Warning messages:
1: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition
2: In plot.xy(xy, type, ...) :
  plot type 'black' will be truncated to first character
3: In doTryCatch(return(expr), name, parentenv, handler) :
  plot type 'black' will be truncated to first character
>

**Comment by plzmsu** [comment]
Lab5 render alone:

Output created: docs/lab5_variograms.html
Warning messages:
1: In system2("/usr/bin/otool", c("-L", shQuote(DSO)), stdout = TRUE) :
  running command ''/usr/bin/otool' -L '/Library/Frameworks/R.framework/Resources/library/tcltk/libs//tcltk.so'' had status 1
2: some mark values are NA in the point pattern Y 
3: some mark values are NA in the point pattern object

**Comment by plzmsu** [comment]
i've been able to push 1 lab at a time and it's working. I'll hold off on updating the lab4 docs since they are working on it this week.
